### PR TITLE
Added the ability to make the window transparent

### PR DESCRIPTION
**Pull request by andrewreedy**

### CODE REVIEW

**Comment by jeff-h** [comment]
This looks like a useful function — can someone try this out and confirm it's working for them? Also, @andrewreedy would you be happy to put some documentation together for this?

**Comment by andrewreedy** [comment]
yea no problem!

**Comment by andrewreedy** [comment]
Yea its cool if you want to get that transparent look like in some of the terminal themes https://www.dropbox.com/s/b0g8c6t4j7un6jd/Screenshot%202015-03-06%2000.15.37.png?dl=0

**Comment by jeff-h** [comment]
In the interests of momentum and enthusiasm, I'm merging this.

**Pull request merged**
